name = "Snopt"
uuid = "0e9dc826-d618-11e8-1f57-c34e87fde2c0"
authors = ["Andrew Ning <aning@byu.edu> and contributors"]
version = "0.2.3"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
